server:
  port: 8080
  servlet:
    context-path: D:\PClearning\springboot_SimulationSystem\springboot-test/ # ????

spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

#??Mybatis??????????
mybatis:
  configuration:
    map-underscore-to-camel-case: true